(require 'ini)

(defun kubectl--ini-read (ini-config-alist profile key)
  (cdr (assoc key (cdr (assoc profile ini-config-alist)))))

(defun kubectl--get-summary ()
  (let* ((kube-config-filename "~/.kube/config")
         (pd-kubectx-config (ini-decode "~/.pd-kubectx/config"))
         (ini-profile "DEFAULT")
         (current-context-name (kubectl--ini-read pd-kubectx-config ini-profile "context"))
         (current-context (kubectl--ini-read pd-kubectx-config ini-profile "context"))
         (available-contexts (kubectl--get-available-contexts))
         (aws-profiles (kubectl--get-aws-profiles))
         (context (-concat `(
                             ("cluster" ,current-context-name))
                           `(("resources" ,(if kubectl-all-namespaces
                                               kubectl-resources-current-all-ns
                                             kubectl-resources-current)))
                           `(("role" ,(format "%s/%s" (getenv "AWS_OKTA_PROFILE") (getenv "AWS_OKTA_ASSUMED_ROLE"))))
                           `(("pulling" ,(if kubectl-is-pulling "true" "false")))
                           `(("auto" ,(if kubectl-autorefresh "true" "false")))
                           ;; `(("expires" ,(kubectl--get-remaining-time)))
                           )))
    (setq kubectl-available-contexts available-contexts
          kubectl-current-context current-context-name
          kubectl-current-cluster current-context-name
          kubectl-current-namespace (if kubectl-all-namespaces
                                        "All Namespaces"
                                      (kubectl--ini-read pd-kubectx-config ini-profile "namespace"))
          kubectl-aws-profiles aws-profiles)
    context))

(defun kubectl--get-remaining-time ()
  (let* ((remaining-time (time-subtract (seconds-to-time (string-to-number (getenv "AWS_OKTA_SESSION_EXPIRATION"))) (current-time)))
         (expired (eq (car remaining-time) -1))
         (remaining-minutes (/ (cadr remaining-time ) 60))
         (color (cond
                 ((and (> remaining-minutes 15) (not expired)) "fairy-mint-800")
                 ((and (< remaining-minutes 15) (not expired)) "fairy-gold-800")
                 (expired "fairy-carrot-600"))))
    (kubectl--color (format "%s%sm" (if expired "-" "") (number-to-string remaining-minutes)) color)))

(defun kubectl--color (text color)
  (let* ((colors '(("fairy-sky-100"      "#def8ff")
                   ("fairy-sky-200"      "#cdf5ff")
                   ("fairy-sky-300"      "#bbf1ff")
                   ("fairy-sky-400"      "#aaeeff")
                   ("fairy-sky-500"      "#99ebff")
                   ("fairy-sky-600"      "#7ae4fe")
                   ("fairy-sky-700"      "#5bddfd")
                   ("fairy-sky-800"      "#3dd6fc")
                   ("fairy-sky-900"      "#1ecffb")
                   ("fairy-sky-1000"     "#00c0f0")
                   ("fairy-grape-100"    "#ede7f3")
                   ("fairy-grape-200"    "#e3d6f6")
                   ("fairy-grape-300"    "#d9c5f9")
                   ("fairy-grape-400"    "#cfb4fc")
                   ("fairy-grape-500"    "#c5a3ff")
                   ("fairy-grape-600"    "#b78dfe")
                   ("fairy-grape-700"    "#aa77fd")
                   ("fairy-grape-800"    "#9d62fd")
                   ("fairy-grape-900"    "#904cfc")
                   ("fairy-grape-1000"   "#5a00f5")
                   ("fairy-mint-100"     "#fbfefc")
                   ("fairy-mint-200"     "#f2fdf6")
                   ("fairy-mint-300"     "#eafcf0")
                   ("fairy-mint-400"     "#e1fbeb")
                   ("fairy-mint-500"     "#c2ffdf")
                   ("fairy-mint-600"     "#b9fbd1")
                   ("fairy-mint-700"     "#a2fcc3")
                   ("fairy-mint-800"     "#8afdb4")
                   ("fairy-mint-900"     "#73fea6")
                   ("fairy-mint-1000"    "#5cff98")
                   ("fairy-gold-100"     "#fef9b8")
                   ("fairy-gold-200"     "#fef693")
                   ("fairy-gold-300"     "#fef36e")
                   ("fairy-gold-400"     "#fff352")
                   ("fairy-gold-500"     "#feed24")
                   ("fairy-gold-600"     "#ffea00")
                   ("fairy-gold-700"     "#efdb00")
                   ("fairy-gold-800"     "#e6c000")
                   ("fairy-gold-900"     "#d0be01")
                   ("fairy-gold-1000"    "#c0b001")
                   ("fairy-carrot-100"   "#ffd4d1")
                   ("fairy-carrot-200"   "#fec4c0")
                   ("fairy-carrot-300"   "#fdb4af")
                   ("fairy-carrot-400"   "#fca49e")
                   ("fairy-carrot-500"   "#fb948d")
                   ("fairy-carrot-600"   "#fb847c")
                   ("fairy-carrot-700"   "#fa6d64")
                   ("fairy-carrot-800"   "#f9564c")
                   ("fairy-carrot-900"   "#f84034")
                   ("fairy-carrot-1000"  "#f7291c")
                   ("fairy-blush-100"    "#fec8db")
                   ("fairy-blush-200"    "#fdb6cf")
                   ("fairy-blush-300"    "#ffb8d1")
                   ("fairy-blush-400"    "#fc92b8")
                   ("fairy-blush-500"    "#fb80ac")
                   ("fairy-blush-600"    "#fb6ea0")
                   ("fairy-blush-700"    "#fa5c95")
                   ("fairy-blush-800"    "#fa4a89")
                   ("fairy-blush-900"    "#f9387d")
                   ("fairy-blush-1000"   "#f92672")
                   ("fairy-space-100"    "#f8f8f2")
                   ("fairy-space-200"    "#e1e1d9")
                   ("fairy-space-300"    "#cacac1")
                   ("fairy-space-400"    "#b3b3a9")
                   ("fairy-space-500"    "#9c9c91")
                   ("fairy-space-600"    "#868678")
                   ("fairy-space-700"    "#6f6f60")
                   ("fairy-space-800"    "#585848")
                   ("fairy-space-900"    "#414130")
                   ("fairy-space-1000"   "#2b2b18")))
         (hexcode (cadr (assoc color colors))))
    (propertize text 'face `(:foreground ,hexcode))))

(provide 'kubectl-summary)
